# Setup
title:               newurbanist

tagline:                       sustainable development word vomit
description:         unhinged pedestrian energy
url:                 https://newurbanist.github.io
baseurl:             ''

paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jen Fox
  url:               https://twitter.com/jenfox54
  email:             jenfox54@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
